### ISSUE TITLE
Importing ZIP file as newest module version via module importer in forge fails to succeed.

### ISSUE THREAD

**Issue by Szyna1988** [BoltsJ/ffg-pool-party#4]
<details>
<summary>Basic information</summary>

 - Pool Party version: 0.2
 - Foundry VTT version: 10.303

</details>

### Description of the issue

While installing through foundry module manager, the pool party fails to work. Downloading a zip file from github (with v10 compatibility merged) and importing this zip via forge module import seems to be succesful, but after launching foundry module is nowhere to be seen. 

**To Reproduce**
1. Download zip file from pool party github
2. In forge vtt manager click configure
3. Choose Summon Import wizard
4. Navigate to zip file with updated module files
5. Click import. 

**Expected behavior**
The forge finds the module in the zip file, shows that it has been imported, but the module fails to load ingame nonetheless.

**Additional context**
Most likely the forge has some issue with installing this module via ZIP file. Compiling a new release and allowing the installation of the updated files via new module.json link might most likely solve the issue.

**Comment by BoltsJ** [comment]
I haven't made a release yet.

**Comment by BoltsJ** [comment]
Also, the forge isn't a supported platform, you'll need to either contact their support or replicate the issue from the desktop app or a self-hosted instance.
